# Add TIMESTAMP to read model (auto-generated by DB).

from pydantic import BaseModel, Field, conint, confloat, constr


class MachineCreate(BaseModel):
    MACHINE_ID: constr(strip_whitespace=True, min_length=1, max_length=128)
    MACHINE_NAME: constr(strip_whitespace=True, min_length=1, max_length=256)
    CPU_CORES: conint(ge=1, le=4096)
    RAM_USED: conint(ge=0)
    RAM_TOTAL: conint(ge=0)
    STORAGE_USED: conint(ge=0)
    STORAGE_TOTAL: conint(ge=0)
    CPU_TEMPS: confloat(ge=-40.0, le=150.0) = Field(..., description="Average CPU temp (°C)")
    NETWORK_USAGE: conint(ge=0)


class MachineRead(MachineCreate):
    TIMESTAMP: str
